### PR TITLE
Fixed Project

### PR DESCRIPTION
**Pull request by gordofreemo**
Hello, 
I have fixed the project here. Removed all league of legends. it better now
please accept pull

### CODE REVIEW

**Comment by marczeugs** [comment]
Thank you for your suggestion. I do agree with the gist of your pull request, please do consider the following though: don't care didn't ask + don't care + ratio + cope + counter ratio + skill issue + cry about it + pinged owner + seethe + mald + stfu + no life + exposed + canceled + no life + denied + rat + counter ratio + backpilled + cancelled + stay mad

**Comment by marczeugs** [comment]
\+ rat

**Comment by gordofreemo** [comment]
bro why are you giving me email notifications 4 years later

**Comment by marczeugs** [comment]
🚀🚀🚀

**Pull request closed without merging**
